"""Scene 6 - Radial Functions and Applications (voiceover-timed).

From the heart, back to the composition shape, decompose it, and show that each
angular component Y_l^m is multiplied by a RADIAL function R_l(r). Choosing R_l(r)
selects the phenomenon; the angular shape and the radial physics are separated.
"""
from style import *
from manim_voiceover import VoiceoverScene

configure()

RES = (48, 24)
SMALL_R = 1.2
SIDE_X = 3.7
BIG_R = 1.6
HEART_RED = "#E8455F"
BASIS = [(2, 0), (3, 2), (4, 4)]
SUM_TERMS = [(2, 0, 1.0), (3, 2, 1.0), (4, 4, 1.0)]

M1 = ("Ok, but how do we actually use spherical harmonics to explain different "
      "phenomena, such as gravity?")
M2 = ("Let's go back to our weird shape that was a composition of a few spherical "
      "harmonics.")
M3 = "Thanks to the fact that we have this shape decomposed,"
M4 = ("we can determine how each component influences the surrounding space: we "
      "multiply each spherical-harmonic component by a radial function.")
M5 = ("By changing these radial functions, we can analyze different phenomena - for "
      "example, express the gravitational field generated by our shape. Of course, "
      "deriving such formulas is not an easy task, but note the beauty of this "
      "approach: we have effectively separated the analysis of the shape from the "
      "physical phenomena it generates. This is why spherical harmonics are so "
      "powerful, and why they can be used in so many fields - including gravity, "
      "quantum mechanics, geophysics, and computer graphics.")
M6 = ("I hope this gives a short, intuitive introduction to spherical harmonics. "
      "There are multiple great resources that cover the actual math behind the topic "
      "- I reference a few in the video description. I wanted to focus on the "
      "intuitive, geometrical picture. Hopefully I've managed to accomplish that at "
      "least to some extent.")


def _field_sphere(field, R):
    s = make_sphere(2.0, res=RES, checker=False).scale(R / SPHERE_R)
    color_surface_by_field(s, field, nu=RES[0], nv=RES[1], v_range=(0, np.pi))
    return s


def _ylm(l, m):
    return lambda u, v: real_Y(l, m, v, u)


def _composition():
    s = Surface(sh_radius_surf(SUM_TERMS, R=BIG_R, amp=0.42),
                u_range=[0, TAU], v_range=[0, np.pi], resolution=RES,
                checkerboard_colors=False, stroke_width=SW_SURF, fill_opacity=1.0)
    color_surface_by_field(s, sh_field(SUM_TERMS), nu=RES[0], nv=RES[1],
                           v_range=(0, np.pi))
    return s


class S6Radial(VoiceoverScene, ThreeDScene):
    def construct(self):
        setup_voice(self)
        self.set_camera_orientation(phi=32 * DEGREES, theta=-90 * DEGREES)
        heart = Surface(heart_surface(R=BIG_R), u_range=[0, TAU], v_range=[0, np.pi],
                        resolution=RES, checkerboard_colors=False,
                        stroke_width=SW_SURF, fill_opacity=1.0)
        heart.set_fill(ManimColor(HEART_RED), 1.0)
        heart.set_stroke(ManimColor(HEART_RED), width=0.3, opacity=0.4)
        self.add(heart)
        S = heart

        # ---- M1: pose the question (hold the heart) ---------------------- #
        with self.voiceover(text=M1) as vo:
            self.wait(vo.duration)

        # ---- M2: heart -> composition shape ------------------------------ #
        with self.voiceover(text=M2) as vo:
            self.move_camera(phi=70 * DEGREES, theta=-90 * DEGREES,
                             added_anims=[Transform(S, _composition())],
                             run_time=vo.duration)

        # ---- M3: decompose into components ------------------------------- #
        left = _field_sphere(_ylm(*BASIS[0]), SMALL_R).move_to(LEFT * SIDE_X)
        center = _field_sphere(_ylm(*BASIS[1]), SMALL_R)
        right = _field_sphere(_ylm(*BASIS[2]), SMALL_R).move_to(RIGHT * SIDE_X)
        plus_l = MathTex("+", font_size=FS_TITLE).move_to([-SIDE_X / 2, 0, 0])
        plus_r = MathTex("+", font_size=FS_TITLE).move_to([SIDE_X / 2, 0, 0])
        ylabels = VGroup()
        for (l, m), x in zip(BASIS, (-SIDE_X, 0, SIDE_X)):
            ylabels.add(MathTex(rf"Y_{{{l}}}^{{{m}}}", font_size=FS_MATH)
                        .move_to([x, 0, -SMALL_R - 0.55]))
        with self.voiceover(text=M3) as vo:
            d = vo.duration
            self.play(ReplacementTransform(S, center),
                      TransformFromCopy(S, left), TransformFromCopy(S, right),
                      run_time=d * 0.7)
            self.add_fixed_orientation_mobjects(plus_l, plus_r, *ylabels)
            self.play(Write(plus_l), Write(plus_r),
                      *[FadeIn(y) for y in ylabels], run_time=d * 0.3)

        # ---- M4: radial function above each + general formula ------------ #
        rlabels = VGroup()
        for (l, m), x in zip(BASIS, (-SIDE_X, 0, SIDE_X)):
            rlabels.add(MathTex(rf"R_{{{l}}}(r)\,\cdot", font_size=FS_MATH, color=COMP)
                        .move_to([x, 0, SMALL_R + 0.65]))
        formula = MathTex(r"f(r,\theta,\phi)=\sum_{\ell,m} R_\ell(r)\,c_{\ell m}\,"
                          r"Y_\ell^m(\theta,\phi)", font_size=FS_MATH).to_edge(DOWN, buff=0.6)
        with self.voiceover(text=M4) as vo:
            d = vo.duration
            self.add_fixed_orientation_mobjects(*rlabels)
            self.play(*[Write(r) for r in rlabels], run_time=d * 0.4)
            self.add_fixed_in_frame_mobjects(formula)
            self.play(Write(formula), run_time=d * 0.5)
            self.wait(d * 0.1)

        # ---- M5: applications -- spin each basis sphere (3 slow turns) ---- #
        with self.voiceover(text=M5) as vo:
            self.play(
                Rotate(left, angle=3 * TAU, axis=OUT, about_point=left.get_center()),
                Rotate(center, angle=3 * TAU, axis=OUT, about_point=center.get_center()),
                Rotate(right, angle=3 * TAU, axis=OUT, about_point=right.get_center()),
                run_time=vo.duration, rate_func=linear,
            )

        # ---- M6: outro (hold, then fade out) ----------------------------- #
        with self.voiceover(text=M6) as vo:
            self.wait(vo.duration)
        self.play(FadeOut(left), FadeOut(center), FadeOut(right),
                  FadeOut(plus_l), FadeOut(plus_r), FadeOut(ylabels),
                  FadeOut(rlabels), FadeOut(formula), run_time=1.2)
        self.wait(0.3)
